module.exports.patientDataList = [
  {
    id: 1,
    first_name: "Michael",
    last_name: "Scott",
    gender: "Male",
    username: "Mic123",
    avatar: "https://upload.wikimedia.org/wikipedia/en/d/dc/MichaelScott.png",
    date_of_birth: "Jul 12 1980",
    profile_decription: "I love vaccines!",
    phone_number: "416-123-1234",
    email_address: "Michael123@gmail.com",
    address: "23 Dundas St. Toronto, ON",
    insurance_member_id: "12345ABCDEF",
    insurance_policy_number: "12345678YZ",
    insurance_plan_name: "OHIP",
    medical_history_id: ""
  },
  {
    id: 2,
    first_name: "Michael",
    last_name: "Scott",
    gender: "Male",
    username: "Mic123",
    avatar: "https://upload.wikimedia.org/wikipedia/en/d/dc/MichaelScott.png",
    date_of_birth: "Jul 12 1980",
    profile_decription: "I love vaccines!",
    phone_number: "416-123-1234",
    email_address: "Michael123@gmail.com",
    address: "23 Dundas St. Toronto, ON",
    insurance_member_id: "12345ABCDEF",
    insurance_policy_number: "12345678YZ",
    insurance_plan_name: "OHIP",
    medical_history_id: ""
  },
  {
    id: 3,
    first_name: "Michael",
    last_name: "Scott",
    gender: "Male",
    username: "Mic123",
    avatar: "https://upload.wikimedia.org/wikipedia/en/d/dc/MichaelScott.png",
    date_of_birth: "Jul 12 1980",
    profile_decription: "I love vaccines!",
    phone_number: "416-123-1234",
    email_address: "Michael123@gmail.com",
    address: "23 Dundas St. Toronto, ON",
    insurance_member_id: "12345ABCDEF",
    insurance_policy_number: "12345678YZ",
    insurance_plan_name: "OHIP",
    medical_history_id: ""
  },
  {
    id: 4,
    first_name: "Michael",
    last_name: "Scott",
    gender: "Male",
    username: "Mic123",
    avatar: "https://upload.wikimedia.org/wikipedia/en/d/dc/MichaelScott.png",
    date_of_birth: "Jul 12 1980",
    profile_decription: "I love vaccines!",
    phone_number: "416-123-1234",
    email_address: "Michael123@gmail.com",
    address: "23 Dundas St. Toronto, ON",
    insurance_member_id: "12345ABCDEF",
    insurance_policy_number: "12345678YZ",
    insurance_plan_name: "OHIP",
    medical_history_id: ""
  },
  {
    id: 5,
    first_name: "Michael",
    last_name: "Scott",
    gender: "Male",
    username: "Mic123",
    avatar: "https://upload.wikimedia.org/wikipedia/en/d/dc/MichaelScott.png",
    date_of_birth: "Jul 12 1980",
    profile_decription: "I love vaccines!",
    phone_number: "416-123-1234",
    email_address: "Michael123@gmail.com",
    address: "23 Dundas St. Toronto, ON",
    insurance_member_id: "12345ABCDEF",
    insurance_policy_number: "12345678YZ",
    insurance_plan_name: "OHIP",
    medical_history_id: ""
  },
  {
    id: 6,
    first_name: "Michael",
    last_name: "Scott",
    gender: "Male",
    username: "Mic123",
    avatar: "https://upload.wikimedia.org/wikipedia/en/d/dc/MichaelScott.png",
    date_of_birth: "Jul 12 1980",
    profile_decription: "I love vaccines!",
    phone_number: "416-123-1234",
    email_address: "Michael123@gmail.com",
    address: "23 Dundas St. Toronto, ON",
    insurance_member_id: "12345ABCDEF",
    insurance_policy_number: "12345678YZ",
    insurance_plan_name: "OHIP",
    medical_history_id: ""
  },
  {
    id: 7,
    first_name: "Michael",
    last_name: "Scott",
    gender: "Male",
    username: "Mic123",
    avatar: "https://upload.wikimedia.org/wikipedia/en/d/dc/MichaelScott.png",
    date_of_birth: "Jul 12 1980",
    profile_decription: "I love vaccines!",
    phone_number: "416-123-1234",
    email_address: "Michael123@gmail.com",
    address: "23 Dundas St. Toronto, ON",
    insurance_member_id: "12345ABCDEF",
    insurance_policy_number: "12345678YZ",
    insurance_plan_name: "OHIP",
    medical_history_id: ""
  },
  {
    id: 8,
    first_name: "Michael",
    last_name: "Scott",
    gender: "Male",
    username: "Mic123",
    avatar: "https://upload.wikimedia.org/wikipedia/en/d/dc/MichaelScott.png",
    date_of_birth: "Jul 12 1980",
    profile_decription: "I love vaccines!",
    phone_number: "416-123-1234",
    email_address: "Michael123@gmail.com",
    address: "23 Dundas St. Toronto, ON",
    insurance_member_id: "12345ABCDEF",
    insurance_policy_number: "12345678YZ",
    insurance_plan_name: "OHIP",
    medical_history_id: ""
  },
  {
    id: 9,
    first_name: "Michael",
    last_name: "Scott",
    gender: "Male",
    username: "Mic123",
    avatar: "https://upload.wikimedia.org/wikipedia/en/d/dc/MichaelScott.png",
    date_of_birth: "Jul 12 1980",
    profile_decription: "I love vaccines!",
    phone_number: "416-123-1234",
    email_address: "Michael123@gmail.com",
    address: "23 Dundas St. Toronto, ON",
    insurance_member_id: "12345ABCDEF",
    insurance_policy_number: "12345678YZ",
    insurance_plan_name: "OHIP",
    medical_history_id: ""
  },
  {
    id: 10,
    first_name: "Michael",
    last_name: "Scott",
    gender: "Male",
    username: "Mic123",
    avatar: "https://upload.wikimedia.org/wikipedia/en/d/dc/MichaelScott.png",
    date_of_birth: "Jul 12 1980",
    profile_decription: "I love vaccines!",
    phone_number: "416-123-1234",
    email_address: "Michael123@gmail.com",
    address: "23 Dundas St. Toronto, ON",
    insurance_member_id: "12345ABCDEF",
    insurance_policy_number: "12345678YZ",
    insurance_plan_name: "OHIP",
    medical_history_id: ""
  },
  {
    id: 11,
    first_name: "Michael",
    last_name: "Scott",
    gender: "Male",
    username: "Mic123",
    avatar: "https://upload.wikimedia.org/wikipedia/en/d/dc/MichaelScott.png",
    date_of_birth: "Jul 12 1980",
    profile_decription: "I love vaccines!",
    phone_number: "416-123-1234",
    email_address: "Michael123@gmail.com",
    address: "23 Dundas St. Toronto, ON",
    insurance_member_id: "12345ABCDEF",
    insurance_policy_number: "12345678YZ",
    insurance_plan_name: "OHIP",
    medical_history_id: ""
  },
  {
    id: 12,
    first_name: "Michael",
    last_name: "Scott",
    gender: "Male",
    username: "Mic123",
    avatar: "https://upload.wikimedia.org/wikipedia/en/d/dc/MichaelScott.png",
    date_of_birth: "Jul 12 1980",
    profile_decription: "I love vaccines!",
    phone_number: "416-123-1234",
    email_address: "Michael123@gmail.com",
    address: "23 Dundas St. Toronto, ON",
    insurance_member_id: "12345ABCDEF",
    insurance_policy_number: "12345678YZ",
    insurance_plan_name: "OHIP",
    medical_history_id: ""
  }

]